---
title: Umbrella
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    Work Description: 'We work with everyone from post investment startups, to SME’s
      and global brands and deliver a full creative service from brand strategy to
      packaging, imagery production, campaigns and everything in between. With the
      right team, anything is possible.

'
  roles:
    title: Roles
    output: true
  team:
    title: Team
    output: true
  undercover:
    title: Undercover
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: projects
  values:
    Project Images:
    - Image: 
    Services:
    - Service Type: 
    Project Cover Image: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
